title: HackmasterDiary
description: Coursework diary and homework write-ups
baseurl: "/HackmasterDiary"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
